[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "pie-boot"
repository.workspace = true
version.workspace = true

[features]
hv = []

[dependencies]
kdef-pgtable = {workspace = true}
pie-boot-if = {workspace = true}
pie-boot-macros = {path = "macros/pie-boot-macros"}

[target.'cfg(target_arch = "aarch64")'.dependencies]
kasm-aarch64 = {path = "macros/kasm-aarch64"}

[build-dependencies]
kdef-pgtable = {path = "../kdef-pgtable"}
pie-boot-arm-loader = {path = "../loader/pie-boot-arm-loader", artifact = "bin", target = "aarch64-unknown-none"}
