[package]
name = "pie-boot"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[features]
hv = []


[dependencies]
pie-boot-if = { workspace = true }
pie-boot-macros = { path = "macros/pie-boot-macros" }
kdef-pgtable = { path = "../kdef-pgtable" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
kasm-aarch64 = { path = "macros/kasm-aarch64" }


[build-dependencies]
kdef-pgtable = { path = "../kdef-pgtable" }
