[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "pie-boot"
repository.workspace = true
version = "0.1.1"

[features]
hv = []

[dependencies]
kdef-pgtable = {workspace = true}
pie-boot-if = {workspace = true}
pie-boot-macros = {path = "macros/pie-boot-macros", version = "0.1"}

[target.'cfg(target_arch = "aarch64")'.dependencies]
kasm-aarch64 = {path = "macros/kasm-aarch64", version = "0.1"}

[build-dependencies]
kdef-pgtable = {workspace = true}
pie-boot-loader-aarch64 = {path = "../loader/pie-boot-loader-aarch64", artifact = "bin", target = "aarch64-unknown-none", version = "0.1"}
