[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "pie-boot"
repository.workspace = true
version = "0.1.1"

[features]
hv = []

[dependencies]
kdef-pgtable = {workspace = true}
pie-boot-if = {workspace = true}
pie-boot-macros = {path = "macros/pie-boot-macros", version = "0.1"}

[target.'cfg(target_arch = "aarch64")'.dependencies]
kasm-aarch64 = {path = "macros/kasm-aarch64", version = "0.1"}

[build-dependencies]
kdef-pgtable = {workspace = true}
# TODO: 目前必须使用 target = "target"，否则在依赖中不会编译 bin, issue: https://github.com/rust-lang/cargo/issues/15095
pie-boot-loader-aarch64 = {path = "../loader/pie-boot-loader-aarch64", artifact = "bin", target = "target", version = "0.1"}
